### ISSUE TITLE
What GSC Compiler do you use

### ISSUE THREAD

**Issue by ghost** [HuthTV/BO2-Persistent-Upgrades-Bank#1]
What GSC Compiler do you use, because when I Compile with GSC studio plutonium crashes

**Comment by HuthTV** [comment]
It's compiled using GSC studio BETA 16.2.15.0. Verified it works for me today. No issues.

**Comment by HuthTV** [comment]
It's compiled using GSC studio BETA 16.2.15.0. Verified it works for me today. No issues.

**Comment by HuthTV** [comment]
It's compiled using GSC studio BETA 16.2.15.0. Verified it works for me today. No issues. What error message are you getting?

**Comment by ghost** [comment]
i fixed it i used the gsc tool kit on pluto site
